#!/usr/bin/env bash
# pomf.se uploader
# requires: curl, jq
# Works in dash!

upload_url='https://pomf.space/upload.php'
return_url='https://a.pomf.space'

# Alternatives:

#upload_url='https://pomf.cat/upload.php'
#return_url='https://a.pomf.cat'

#upload_url='https://mixtape.moe/upload.php'
#return_url='https://my.mixtape.moe'

usage()
{
	echo "USAGE: $0 FILES"
        exit 1
}

[ -n "$1" ] || { echo 'No filename given!';   usage; } 
[ -f "$1" ] || { echo 'File does not exist!'; usage; }  
 
json_out="$(curl --form files[]=@"$@" $upload_url)"
remote_filename="$(echo $json_out | jq -r '.files[0].url')"
success=$(echo $json_out | jq -r '.success')

if [ $success = true ]
then
	file_url="$return_url/$(basename $remote_filename)"
	echo "$file_url" 
	echo "$file_url" | xclip -in -sel clip
	beep
else
	echo 'File upload unsuccessful!'
	exit 1
fi
